"""
src/models/reports.py
Pydantic contract for the final consolidated report emitted by a workflow run.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

import pytz
from pydantic import BaseModel, Field

from src.models.recommendations import BuyCandidate, StockDecision

_IST = pytz.timezone("Asia/Kolkata")

_SEBI_DISCLAIMER = (
    "This report is generated by an automated AI system and constitutes "
    "RECOMMENDATIONS ONLY. It does not represent SEBI-registered investment advice. "
    "Past performance is not indicative of future results. Trade at your own risk."
)


def _now_ist() -> datetime:
    return datetime.now(_IST)


# A decision can be either a hold/sell decision or a buy candidate.
AnyDecision = Annotated[StockDecision | BuyCandidate, Field(discriminator=None)]


class FinalReport(BaseModel):
    """Consolidated output of a full workflow run, ready for display or persistence."""

    timestamp: datetime = Field(default_factory=_now_ist)
    workflow_type: Literal["BUYER", "SELLER", "PORTFOLIO_REVIEW"]
    decisions: list[StockDecision | BuyCandidate] = Field(default_factory=list)
    summary: str = Field(min_length=1, description="One-paragraph natural-language summary")
    disclaimer: str = Field(default=_SEBI_DISCLAIMER)

    @property
    def decision_count(self) -> int:
        return len(self.decisions)

    @property
    def sell_decisions(self) -> list[StockDecision]:
        return [d for d in self.decisions if isinstance(d, StockDecision) and d.action == "SELL"]

    @property
    def hold_decisions(self) -> list[StockDecision]:
        return [d for d in self.decisions if isinstance(d, StockDecision) and d.action == "HOLD"]

    @property
    def buy_candidates(self) -> list[BuyCandidate]:
        return [d for d in self.decisions if isinstance(d, BuyCandidate)]
